name: tests-installations
on: [push]
jobs:
  nvim: 
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: bash "${GITHUB_WORKSPACE}/nvim/install.bash"
        shell: bash
      - run: bash "${GITHUB_WORKSPACE}/nvim/tests.bash"
        shell: bash
  kitty: 
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: bash "${GITHUB_WORKSPACE}/kitty/install.bash"
        shell: bash
      - run: bash "${GITHUB_WORKSPACE}/kitty/test.bash"
        shell: bash
  fish: 
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: bash "${GITHUB_WORKSPACE}/fish/install.bash"
        shell: bash
      - run: bash "${GITHUB_WORKSPACE}/fish/test.bash"
        shell: bash
  # fonts: 
  #   runs-on: ubuntu-20.04
  #   steps:
  #     - uses: actions/checkout@v2
  #       with:
  #         ref: modular
  #         fetch-depth: 1
  #     - run: bash "${GITHUB_WORKSPACE}/fonts/install.bash"
  #       shell: bash
  git: 
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: bash "${GITHUB_WORKSPACE}/git/install.bash"
        shell: bash
      - run: bash "${GITHUB_WORKSPACE}/git/test.bash"
        shell: bash
  tmux: 
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt-get update && sudo apt-get install -y tmux 
      - run: bash "${GITHUB_WORKSPACE}/tmux/install.bash"
        shell: bash
      - run: bash "${GITHUB_WORKSPACE}/tmux/test.bash"
        shell: bash
